product_save.download:
  path: '/theme-demo-download/{name}'
  defaults:
    _controller: '\Drupal\product_save\EventSubscriber\OrderCompleteSubscriber::Render'
    _title: 'Theme Download'
  requirements:
    _permission: '\Drupal\product_save\EventSubscriber\OrderCompleteSubscriber::Permission'

